#!/bin/bash
 

# ---------------------------------------------------------------FUNCTIONS------------------------------------------------------------------------------------

my_laptop(){

# pasword prompt settings for fingerprint
sudo pam-auth-update
# beter sound control panel (mute right microphone on laptop)
sudo apt install pavucontrol -yy
#(power saving tool)
sudo add-apt-repository ppa:slimbook/slimbook
sudo apt update && sudo apt install slimbookbattery -yy

}

remove_snaps () {

# remove snaps
sudo systemctl disable apport
sudo rm -rf /var/cache/snapd/
sudo apt-get autoremove --purge snapd gnome-software-plugin-snap -yy
rm -fr ~/snap
sudo apt-get remove --purge gnome-software-plugin-snap -yy
sudo apt-get autoremove -y
}

clear_gnome(){
# install clear gnome desktop
sudo apt-get install gnome-session -yy
sudo update-alternatives --config gdm3.css -yy
}

over_ampliphication(){
# allow for volume over 100%
gsettings set org.gnome.desktop.sound allow-volume-above-100-percent true
# install clear gnome desktop

}

wine1804(){

sudo dpkg --add-architecture i386 
wget -nc https://dl.winehq.org/wine-builds/winehq.key
sudo apt-key add winehq.key
sudo apt-add-repository 'deb http://dl.winehq.org/wine-builds/ubuntu/ artful main'
sudo apt-get update
sudo apt-get install --install-recommends winehq-stable -yy

}


wine1910(){

wget -nc https://dl.winehq.org/wine-builds/winehq.key && sudo apt-key add winehq.key -yy
sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ eoan main'
sudo apt-get update
sudo apt install --install-recommends winehq-devel -yy
}

lutris(){
sudo add-apt-repository ppa:lutris-team/lutris
sudo apt-get update
sudo apt-get install lutris -yy
}

basic_apps(){

sudo apt-get install gnome-calculator -yy
sudo apt-get install gnome-calendar -yy
sudo apt-get install gnome-system-monitor -yy
sudo apt-get install gnome-music -yy
sudo apt-get install totem -yy
sudo apt-get install gnome-contacts -yy
sudo apt-get install gnome-clocks -yy
sudo apt-get install gnome-weather -yy
sudo apt-get install geary -yy
sudo apt-get install gnome-tweaks -yy
sudo apt-get install obs-studio -yy
sudo pat-get install mpv
sudo apt-get -y install libgconf2-4
sudo apt-get remove libreoffice*

}

install_flatpak(){

sudo apt-get install flatpak -yy
sudo apt install gnome-software-plugin-flatpak -yy
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

}

Install_spotify(){

flatpak install flathub com.spotify.Client -yy

}

install_nitroshare(){
sudo add-apt-repository ppa:george-edison55/nitroshare
sudo apt-get update
sudo apt-get install nitroshare
}

install_libreoffice(){

flatpak install flathub org.libreoffice.LibreOffice -yy

}

install_deb_apps(){
sudo dpkg -i ~/Apps/*.deb
}


update_reboot(){


sudo apt-get update -yy
sudo apt-get upgrade -yy
rm $filename
rm winehq.key
sudo reboot

}

choose_options(){

dialog --title "What do you need" --checklist "choose the operations you want to exequte:" 20 50 15 1 Laptop_Mic_And_fingerprint_fix off 2 Remove_SNAPS on 3 Clear_GNOME_Session off 4 Sound_over_ampliphication on 5 Wine_18.04 off 6 Wine_19.10 on 7 Lutris off 8 Basic_GNOME_Apps on 9 Install_Flatpaks on 10 Install_Spotify_flatpak off 11 Install_All_Debs_From_Apps_Folder off 12 Install_Nitroshare off 13 Libre_office_flatpak on 14 Update_And_Reboot on 2>temp_log

echo $result

for line in $(cat $filename)
do



if [ $line == 1 ]
then 
	my_laptop
	printf "\n\n 1) Laptop Microphone And fingerprint fix-setup DONE! \n\n"
fi

if [ $line == 2 ]
then 
	remove_snaps
	printf "\n\n 2)  Remove SNAPS and snapd DONE! \n\n"
fi

if [ $line == 3 ]
then 
	clear_gnome
	printf "\n\n 3) Clear GNOME Session installation DONE! \n\n"
fi

if [ $line == 4 ]
then 
	over_ampliphication
	printf "\n\n 4) Sound over ampliphication enable DONE! \n\n"
fi

if [ $line == 5 ]
then 
	wine1804
	printf "\n\n 5) Wine installation for 18.04 DONE! \n\n"
fi

if [ $line == 6 ]
then 
	wine1904
	printf "\n\n 6) Wine installation for 19.10 DONE! \n\n"
fi

if [ $line == 7 ]
then 
	lutris
	printf "\n\n 7) Lutris installation is DONE! \n\n"
fi

if [ $line == 8 ]
then 
	basic_apps
	printf "\n\n 8) Basic GNOME Apps installation DONE! \n\n"
fi

if [ $line == 9 ]
then 
	install_flatpak
	printf "\n\n 9) Installation of flatpaks and flatpak gnome software extension DONE! \n\n"
fi

if [ $line == 10 ]
then 
	Install_spotify
	printf "\n\n 10) Spotify installation DONE! \n\n"
fi

if [ $line == 11 ]
then 
	install_deb_apps
	printf "\n\n 11)Installation of all debs in Apps folder  DONE! \n\n"
fi

if [ $line == 12 ]
then 
	install_nitroshare
	printf "\n\n 12)Installation of Nitroshare  DONE! \n\n"
fi

if [ $line == 13 ]
then 
	install_libreoffice
	printf "\n\n 13)Installation of Libre Office  DONE! \n\n"
fi

if [ $line == 14 ]
then 
	update_reboot
	printf "\n\n 14)  Bye :) \n\n"
fi
done

}

start(){

dialog --title "What This Is And What The Options mean" --msgbox "
----this is a script that I made in order to install everything I need \n
-----after the installation is complete faster. \n \n


----The scrit requiers your atention it will ask for your password----\n
----------------------------and/or your imput.------------------------\n\n

-------------------------------Options-------------------------------- \n\n

1) Laptop_Mic_And_fingerprint_fix \n 
----this option will open a panel in the terminal, that allows you\n
----to enable the fingerprint sensor for every password prompt.\n
----After that it will install pavucontrol. \n
----On some laptops linix things that you have 2 microphones\n
----when in reality you have only one. So the microphones shows\n
----random behavior in the sound meter. With pavucontrol you can\n 
----mute the right microphone and after that the problem will be fixed. \n
----After all that it will install a power managment toop for laptops \n
----coled slimbook battery 3 \n
2) Remove_SNAPS\n
----this options removes snap apps and the snapd from you system \n
3) Clear GNOME session \n
----this options installs clear gnome seesion, after that \n
----you can go to the gear on the login screen and have \n
----the GNOME experience with out ubuntu's stuff on top of it \n
4) Sound over ampliphication \n
----This option will enable you to raise the volume up to 150% \n
5) Wine_18.04 \n
----This option will install wine *the proper way* for ubntu 18.04\n
6) Wine_19.10 \n
----This option will install wine *the proper way* for ubntu 19.04\n
7) Lutris \n
----This option will install Lutris, Lutris is a program and a website \n
----that makes it easy for you to install windows games thrue WINE with \n
----out you warning about librarys and dependencies \n  
8) Basic_GNOME_Apps \n
----This option will install the following drbian apps in to your system \n
----GNOME calculator, GNOME calendar, GNOME system monitor, GNOME music\n
----GNOME vidos, GNOME contacts, GNOME clocks, GNOME weather \n
----GNOME tweaks , and OBS studio. After that it will add a PPA \n
----for libe ofice \n
9) Install_Flatpaks \n
----This options will insatll Flatpak suport to ubuntu system \n
----and the ubuntu software center \n
10) Install_Spotify (Flatpak)\n
----This option installs the spotify client to your system \n
----Spotify is a very popular music streaming service \n 
----and you can use it for free but with ads \n
11) Install deb files in App folder
----drag and drop every deb applicaiton you want to install in this location\n
---- your-home-folder/App and install them all at once. \n
12) Install_Nitroshare \n
----This option installs nitroshare, nitroshare is a cross platform \n
----application that alows you to share files and forders between computers \n
----connected to your local network. \n
13) Install_libre_office (Flatpak) \n
----istall the latest Libre Office version, a great Microsoft Office \n
----alternative for linux \n 
14) Update_And_Reboot \n
----this option will update your system and then rebooot the PC"  30 80

dialog --title "confirmation" --yesno "Now that you know, do you wish to continue?"  5 60

result="$?"
echo $result

if [  "$result" == 0 ]
then 
	choose_options
fi

}

#-------------------------------------------------------PROGRAM-------------------------------------------------------------------

sudo apt-get install dialog -yy
$result
filename='temp_log'
n=1

start

















